"""Write a /gates status markdown file (canvas when the Cursor dir exists)."""
from __future__ import annotations

import json
import os
from pathlib import Path


def stack_tier(root: Path) -> tuple[str, str]:
    path = root / ".cursor" / "stack-selection.json"
    if not path.is_file():
        return "?", "?"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return "?", "?"
    return str(data.get("stack") or "?"), str(data.get("distribution_tier") or "?")


def next_open_row(root: Path) -> str:
    path = root / "BUILD_PLAN.md"
    if not path.is_file():
        return "(no BUILD_PLAN.md)"
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        # Skip prose that mentions [AGENT] (e.g. Format legend); only numbered/dash rows.
        if not (stripped[:1].isdigit() or stripped.startswith("-")):
            continue
        if "🔲" in line and "[AGENT]" in line:
            return stripped[:120]
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not (stripped[:1].isdigit() or stripped.startswith("-")):
            continue
        if "🔲" in line:
            return stripped[:120]
    return "(no open rows)"


def markdown_report(root: Path, extra_rows: list[tuple[str, str]]) -> str:
    stack, tier = stack_tier(root)
    lines = [
        "# Gate status",
        "",
        f"- Stack: `{stack}`",
        f"- Tier: `{tier}`",
        f"- Next BUILD_PLAN row: {next_open_row(root)}",
        "",
        "| Gate | Result |",
        "| --- | --- |",
    ]
    for name, result in extra_rows:
        lines.append(f"| {name} | {result} |")
    lines.append("")
    return "\n".join(lines)


def canvas_dir() -> Path | None:
    override = os.environ.get("CURSOR_CANVAS_DIR", "").strip()
    if override:
        path = Path(override)
        return path if path.is_dir() else None
    home = Path.home() / ".cursor" / "projects"
    if not home.is_dir():
        return None
    matches = [p / "canvases" for p in home.iterdir() if (p / "canvases").is_dir()]
    return matches[0] if len(matches) == 1 else None


def _canvas_source(rows: list[tuple[str, str]]) -> str:
    encoded = json.dumps([[n, r] for n, r in rows], ensure_ascii=False)
    return (
        'import { H1, Stack, Table, Text } from "cursor/canvas";\n\n'
        f"const ROWS: string[][] = {encoded};\n\n"
        "export default function GatesStatus() {\n"
        "  return (\n"
        "    <Stack gap={16}>\n"
        "      <H1>Gate status</H1>\n"
        '      <Text tone="secondary" size="small">\n'
        "        Generated by scripts/render-gates-status.sh\n"
        "      </Text>\n"
        '      <Table headers={["Gate", "Result"]} rows={ROWS} />\n'
        "    </Stack>\n"
        "  );\n"
        "}\n"
    )


def load_gate_rows(root: Path) -> list[tuple[str, str]]:
    path = root / ".cursor" / "last-feature-gate.json"
    if not path.is_file():
        return [("render-gates-status", "Pass")]
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return [("last-feature-gate.json", "Fail")]
    rows = [(str(name), "Pass") for name in data.get("gates_passed") or []]
    stage = data.get("failed_stage")
    if stage:
        rows.append((str(stage), "Fail"))
    if not rows:
        rows = [("feature-gate", "Pass" if data.get("ok") else "Fail")]
    return rows


def write_status(root: Path, extra_rows: list[tuple[str, str]] | None = None) -> Path:
    rows = extra_rows if extra_rows is not None else load_gate_rows(root)
    md = markdown_report(root, rows)
    dest = root / ".cursor" / "gates-status.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(md, encoding="utf-8", newline="\n")
    canvases = canvas_dir()
    if canvases is not None:
        (canvases / "gates-status.canvas.tsx").write_text(
            _canvas_source(rows), encoding="utf-8", newline="\n"
        )
    return dest


def _json_file(path: Path) -> dict:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def fix_banner(root: Path) -> str:
    strikes = _json_file(root / ".cursor" / "agent-progress.json").get("strikes", 0)
    try:
        strikes_n = int(strikes)
    except (TypeError, ValueError):
        strikes_n = 0
    stage = _json_file(root / ".cursor" / "last-feature-gate.json").get("failed_stage") or "none"
    return f"strikes={strikes_n}\nfailed_stage={stage}\n"
